version: "3"

services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
      - ./api.sql:/docker-entrypoint-initdb.d/dump.sql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api
      MYSQL_PASSWORD: root

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin
    restart: always
    ports:
      - "8035:80"
    environment:
      PMA_HOST: mysql
      PMA_PMADB: phpmyadmin
      MYSQL_ROOT_PASSWORD: root

volumes:
  db_data:
